delete from database by name and id
ECE461/ECE-461-Team pull request #22
Opened 2024-11-08 17:04 UTC by tianayjlin

2024-11-12 18:08 UTC, ealoisel requested changes

2024-11-14 18:41 UTC, henson14 commented on backend/src/database_pg.ts
> +            console.error(`Error deleting ${packageID}`, err.message);
this probably needs to be a Logger call instead of console

2024-11-14 18:41 UTC, henson14 commented on backend/src/database_pg.ts
> +        } catch (err: any) {
needs to be logger instead of console

2024-11-14 18:43 UTC, henson14 commented on backend/src/database_pg.ts
> +
can you add a logging statement that shows how many rows were deleted? this would be useful for once we go into version testing

2024-11-14 18:43 UTC, henson14 commented on backend/src/database_pg.ts
> +            console.log('Closed the database connection.');
same thing here, change this to Logger

2024-11-14 20:04 UTC, ealoisel approved these changes
LGTM

2024-11-14 20:16 UTC, merged